### ISSUE TITLE
App entry points which use a substring of another app entry point will redirect

### ISSUE THREAD

**Issue by TomTirapani** [xh/hoist-dev-utils#29]
If you have an app with two app entry points, and one starts with the name of another, the browser will redirect.

e.g. Entry point `fooBar` will redirect to entry point `foo`.

Not entirely clear on the circumstances - it seems to be fine while at the default route, but will redirect on (certain) subroutes

**Comment by amcclain** [comment]
Fixed in 0e1a46a6de628f1452ec7329a30fe3973b3f9047 - thanks @cnrudd !
